voxpupuli/puppet-splunk

manifests/forwarder.pp
manifests/init.pp
manifests/params.pp

Not only is this a style fix, but thanks to PUP-4520, this would
actually generate wrong results on 4.0 or future parser before 3.8.1.

(MODULES-2096) Move default cases last

---

manifests/forwarder.pp

Without this, $staged_package would be undef in $pkg_path_parts

(MODULES-2953) fix order of assignments

---

manifests/init.pp

Not sure if this is redundant or if things don't work for me because I don't have matching `File` resources

Fix dependencies

---

manifests/forwarder.pp

`splunk_forwarder` tag is used for dependency setting (package, service), so it's essential all configuration items created by `splunk::forwarder` class contains those tags (unless user deliberately decides to override them).

config items are collected with tag - make sure it exists

---

manifests/init.pp

In #31 I added support for the server ensure variable but I didn't actually use it anywhere this fixes that mistake. Sorry about that.

Actually use the variable somewhere

---

lib/puppet/provider/splunk_server/ini_setting.rb
lib/puppet/type/splunk_server.rb

This adds a new splunk_server ini_file resource for configuring the Splunk server config.

Add splunk_server type and provider

---

manifests/init.pp

- If the provider is yum or apt we don't need to use the staging module
and this logic exists in splunk::forwarder.
- Removes an unnecessary include of the staging module.

Add conditional logic for using the staging module

---

manifests/init.pp

- Ensures that all the Splunk resource types are applied in the correct order.
- Depends on #34 and #35 
- I've only tested this on a CentOS 7 node.

Update the resource ordering for the new Splunk types.

---

lib/puppet/provider/splunkforwarder_web/ini_setting.rb
lib/puppet/type/splunkforwarder_web.rb
manifests/forwarder.pp
manifests/init.pp
manifests/platform/posix.pp

- Adds the ability to run Splunk as a non-root user on posix systems.
- Adds the splunkforwarder_web type and provider from Nick Perry's fork.
- Adds purging for all the new Splunk types.
- Provisions all the config files to ensure they exist beforehand.
- Properly tags virtual resources.
- Corrects some permission issues.
- Depends on #37 and this will need a rebase once its merged.

Various updates and fixes

---

README.markdown

- Updates the README to be more consistent with the recent changes to the module.
- Uses the module skeleton README template.
- Depends on #38 for accuracy
- Many of the sections need work, but this is mostly an additive change.

Add a more modern version of our README template with updates.

---

README.markdown
manifests/forwarder.pp
manifests/init.pp

- Change the file mode parameter in the forwarder.pp/init.pp files to
use a string instead of an integer.
- Fixes some issues in the README. I forgot to remove parts of the
template.
- Without this change newer versions of Puppet will fail.

Change file mode to string.

---

Gemfile
manifests/params.pp
spec/acceptance/class_spec.rb
spec/acceptance/nodesets/centos-511-x64.yml
spec/acceptance/nodesets/centos-66-x64.yml
spec/acceptance/nodesets/centos-7-x64.yml
spec/acceptance/nodesets/debian-609-x64.yml
spec/acceptance/nodesets/debian-78-x64.yml
spec/acceptance/nodesets/default.yml
spec/acceptance/nodesets/fedora-20-x64.yml
spec/acceptance/nodesets/ubuntu-1204-x64.yml
spec/acceptance/nodesets/ubuntu-1404-x64.yml
spec/classes/coverage_spec.rb
spec/classes/example_spec.rb
spec/fixtures/hiera.yaml
spec/fixtures/hieradata/default.yaml
spec/spec_helper.rb
spec/spec_helper_acceptance.rb

- Adds the acceptance skeleton from the puppet-module-skeleton.
- Adds initial class_spec tests for Splunk and Splunkforwarder classes.
- Includes the appropriate module dependencies for testing.
- This is just the foundation for adding more tests.

Add acceptance test skeleton.

---

README.markdown

- Adds basic documentation for the Class parameters and various types
that the module provides.

Update README with type documentation.

---

manifests/forwarder.pp

forwarder::pkg_provider should default to $splunk::params::pkg_provider

---

manifests/platform/posix.pp

Prior to this commit, when applying the forwarder class to any agents
the initial run would always fail because the module would attempt to
start the splunk service before it existed. This commit fixes that by
adding a notify param to the provider that sets up that forwarder
service.
Before this commit:
```
May 17 21:41:28 localhost puppet-agent[9660]: Retrieving pluginfacts
May 17 21:41:28 localhost puppet-agent[9660]: Retrieving plugin
May 17 21:41:30 localhost puppet-agent[9660]: Loading facts
May 17 21:41:37 localhost puppet-agent[9660]: Caching catalog for samurai-dog
May 17 21:41:37 localhost puppet-agent[9660]: Applying configuration version '1463521294'
May 17 21:41:37 localhost puppet-agent[9660]: (/Stage[main]/Staging/File[/opt/staging]/ensure) created
May 17 21:41:38 localhost …
```

(maint) Fix resource order for installing splunk forwarders

---

manifests/forwarder.pp

Removed some unneccessary chaining overkill and fixed situations
where the service isn't restarted if you declare splunk forwarder
resources without tags (eg: from a profile)

Fixed service restarts with forwarders

---

CHANGELOG.md
metadata.json

* Added more complete list of OS's to metadata.json
* Changed puppetlabs to voxpupuli in metadata.json
* Lowered Puppet requirement to 3.8.0
* Updated CHANGELOG
* Version bumped to 5.0.0
Closes #54

prepped 5.0.0

---

manifests/forwarder.pp

Modifying `Splunk::Addon` defined types doesn't currently notify the splunk service.
This PR adds a collector chain after the invocation of `create_resources` to ensure that they are set to notify the service

Notify service from addons

---

manifests/forwarder.pp

Further testing after #57 revealed that the package dependancy was also missing causing potential failures with the parent directory of the addon not existing.
In the longer term I am planning to re-engineer a lot of how the dependencies are defined, it's rather over-engineered and the use of virtual resources is pretty overkill - I'll aim to get significant changes into that for 5.1.0 but for now this patch will remove the failure.

added package dependency to splunk::addon types

---

manifests/forwarder.pp

Find it curious that the "file" references in forwarder.pp are not using the variable from the params.pp, small fix. Got the errror when trying to deploy on Windows, but guess it would also occur when using another forwarder_confdir...
For Windows support it seems to me support needs to be added to install the universalforwarder as a chocolatey package, since I don't see how it is gonna work using the msi only...

Make the file reference use the variable and not a fixed path

---

README.md
metadata.json

We currently only run automated tests against Puppet 3 latest and
therefore cannot guarantee that this module works as is expected with
earlier Puppet versions
Bump dependencies to the minimum version that should work under
Puppet 4, based on the metadata

Bump min version_requirement for Puppet + deps

---

manifests/init.pp
manifests/platform/posix.pp

Really useful to set `server_service => 'splunk'` since all the other services are started/stopped by the splunk init.d script.

Allow splunk server services to be overridden

---

lib/puppet/type/splunk_config.rb

The `splunk_config` type needs to load the other `splunk*` types for
purging.  It did this by requiring all of the other ruby files in the
same directory, which, on the client side, includes types from other
modules.  This resulted in type redefinition warnings during the agent
run, and even failures in cases where the other types included libraries
that were not present on the system:
```
Info: Redefining anchor in Puppet::Type
Info: Redefining file_line in Puppet::Type
Info: Redefining firewall in Puppet::Type
Info: Redefining firewallchain in Puppet::Type
Info: Redefining ini_setting in Puppet::Type
Error: Could not autoload puppet/provider/make_server_update/ruby: cannot load such file -- net/http/post/multipart
Error: Could not autoload puppet/type/splunk_config: Could not autoload …
```

splunk_config: Only load other splunk types

---

lib/puppet_x/puppetlabs/splunk/type.rb
spec/unit/puppet/type/splunk_types_spec.rb

A change made in 0fe96f7 to support section headings of the form:
```
foo://bar
```
broke purging, where the underlying inifile type generates resources
with titles like:
```
section/setting
```
When a resource is generated with a title 'foo://bar/setting', the
setting name is not parsed.  This is the case with inputs which often
take on the form:
```
[monitor:///var/log/messages]
setting1 = value1
setting2 = value2
```
The result is an error message: "Error:
/Stage[main]/Splunk::Params/Splunk_config[splunk]: Failed to generate
additional resources using 'generate': Got nil value for setting."  See:
issue #69.
This change looks for additional slashes beyond the '://' and will
parse out the following string as the setting name.
This is not very satisfying because it could break a …

types: Fix purging when section contains '//'

---

manifests/params.pp

The Installdir for windows must contain backslashes.  The default values never worked on windows.  Relates to #100

Fix Windows Forwarder Installdir

---

manifests/params.pp

There was only one 'default' which was 'root', but this user is
non-existent on Windows.

This commit sets the splunk_user for Windows to 'administrator'

---

manifests/forwarder.pp

Prior to this, the file mode for `inputs.conf`, `outputs.conf`, and `web.conf`
would change from `0664` to `0644` on every Puppet run.
On Windows, we don't want to set the file mode for these files as
handling the permissions on these would [best be left](https://docs.puppet.com/puppet/4.10/resources_file_windows.html#consider-using-the-acl-resource-type-instead) for the
[puppetlabs/acl module](https://forge.puppetlabs.com/puppetlabs/acl).

Fix .conf file modes for Windows forwarders

---

README.md
manifests/forwarder.pp
manifests/init.pp

This PR incorporates commits that ultimately allow Windows agents to install packages from UNC paths.
Prior to this, if setting `$package_source` to a UNC path on Windows, the `package` resource wouldn't ever use the value of `$package_source` as it's source. The reason for that is because a UNC path doesn't need to be staged with `staging::file` thus the `$pkg_source` variable was never set.
While I was fixing that problem, I also cleaned up the variable names in the `staging::file` steps to make their intent more clear.

Allow for installing packages from UNC paths on Windows

---

manifests/params.pp

Set `forwarder_install_options` to be `undef` for OS other than Windows.

---

lib/puppet/provider/ini_setting/splunk.rb
lib/puppet/provider/splunk_authentication/ini_setting.rb
lib/puppet/provider/splunk_authorize/ini_setting.rb
lib/puppet/provider/splunk_distsearch/ini_setting.rb
lib/puppet/provider/splunk_indexes/ini_setting.rb
lib/puppet/provider/splunk_input/ini_setting.rb
lib/puppet/provider/splunk_limits/ini_setting.rb
lib/puppet/provider/splunk_output/ini_setting.rb
lib/puppet/provider/splunk_props/ini_setting.rb
lib/puppet/provider/splunk_server/ini_setting.rb
lib/puppet/provider/splunk_transforms/ini_setting.rb
lib/puppet/provider/splunk_web/ini_setting.rb
lib/puppet/provider/splunkforwarder_input/ini_setting.rb
lib/puppet/provider/splunkforwarder_output/ini_setting.rb
lib/puppet/provider/splunkforwarder_props/ini_setting.rb
lib/puppet/provider/splunkforwarder_transforms/ini_setting.rb
lib/puppet/provider/splunkforwarder_web/ini_setting.rb
lib/puppet_x/puppetlabs/splunk/type.rb
spec/splunk_data.rb
spec/unit/puppet/type/splunk_config_spec.rb

Add a new resource parameter that allows redirection of settings into
contexts other than system/local. In prarticular this allows to
customize (and even create) apps with context =>
"apps/<app>/{default,local}". Incidentally this centralises redundant
occurences of system/local as the parameter default.

Allow redirecting of settings into custom contexts

---

manifests/forwarder.pp
manifests/init.pp

When using 'chocolatey' as pkg_provider it is not needed to
include :staging, this is excluded in the init.pp and forwarder.pp

This commit adds the pkg_provider 'chocolatey' to the module

---

README.md
lib/puppet/provider/splunkforwarder_limits/ini_setting.rb
lib/puppet/provider/splunkforwarder_server/ini_setting.rb
lib/puppet/type/splunkforwarder_limits.rb
lib/puppet/type/splunkforwarder_server.rb
manifests/forwarder.pp

This PR adds functionality to allow server.conf and limits.conf to be managed by puppet code. For example one of our use cases:
```
splunkforwarder_limits { 'thruput/maxKBps':
value => $maxkbps,
tag   => 'splunk_forwarder'
}
splunkforwarder_server { 'httpServer/disableDefaultPort':
value => 'true',
tag   => 'splunk_forwarder'
}
```

Added splunkforwarder_server and splunkforwarder_limits providers/types.

---

lib/puppet/type/splunk_config.rb
spec/splunk_data.rb

The splunkforwarder_server type was already created but it wasn't added to splunk_config.rb.  Added.

wire up splunkforwarder_server type

---

manifests/init.pp
manifests/platform/posix.pp
spec/classes/forwarder_spec.rb

when setting up a splunk forwarder on a posix based system you get a warning because the the default parameter for the splunk::platform::posix class is set to $splunk::server_service which doesn't exist when you create a forwarder.  It doesn't exist because it doesn't make sense for a forwarder.  While there should be more cleanup this is a simple non-breaking change to fix the annoying warning.  A bigger refactor would be required to get this done correctly.
#119

SplunkForwarder has no concept of a server_service. 

---

lib/puppet/provider/splunk_alert_actions/ini_setting.rb
lib/puppet/provider/splunk_deploymentclient/ini_setting.rb
lib/puppet/provider/splunk_uiprefs/ini_setting.rb
lib/puppet/provider/splunkforwarder_deploymentclient/ini_setting.rb
spec/splunk_data.rb

This should fix new types/providers to work with this commit: https://github.com/voxpupuli/puppet-splunk/commit/54ece81e6c2938402e32c5f248262303bb2f470f

Fix file_name for several providers

---

lib/puppet/provider/splunk_serverclass/ini_setting.rb
lib/puppet/type/splunk_config.rb
lib/puppet/type/splunk_serverclass.rb
manifests/init.pp
spec/acceptance/splunk_spec.rb
spec/spec_helper_acceptance.rb
spec/splunk_data.rb

Added a new type that allows the creationg of deployment server 'server classes'. 
closes #147

Add serverclass type

---

.sync.yml
.travis.yml
README.md
manifests/forwarder.pp
manifests/init.pp
manifests/params.pp
spec/acceptance/splunk_forwarder_spec.rb

This module used to be able to download splunk installer from splunk directly.  Unfortunately, when splunk updates their http url paths this module didnt get updated as well.  This updates the structure of where the installers should live along with hooking up docker containers for running in travis.  **Merging this would be considered a breaking change since the folder structure where people are placing the installers at on their local file system are changing to match how splunk NOW does it**.
Summary
- Updated expected folder structure for the splunk installers
- Updated Documentation of folder structure
- Updated default download location to be https://download.splunk.com in order to help people use this module easier instead of having to manually prestage the splunk installers.
- …

[BREAKING CHANGE] Updated http download structure

---

metadata.json

**Pull Request (PR) description**
Bump dependency of the puppetlabs/inifile module to handle the newer versions without the PMT tool throwing dependency issues
**This Pull Request (PR) fixes the following issues:**
Fixes #172 
**Task list:**

(maint) Bumping inifile dependency from > 2.0.0 to > 3.0.0

---

lib/puppet_x/puppetlabs/splunk/type.rb

This will allow `puppet generate types` to function
Example:
```
Error: /etc/puppetlabs/code/environments/production/modules/splunk/lib/puppet/type/splunk_alert_actions.rb: title patterns that use procs are not supported.
```
https://tickets.puppetlabs.com/browse/MODULES-4505?focusedCommentId=418416&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-418416
https://github.com/treydock/puppet-module-keycloak/pull/21

Remove unsupported use of proc in title patterns

---

manifests/forwarder.pp
manifests/init.pp
spec/classes/splunk_spec.rb

fix unknown variable: staged_package

---

manifests/forwarder.pp

Ran into issues with getting the splunk forwarder installation working when installing it into a different directory.  splunkforwarder_web passes into splunk's ini_setting for determining the file_path, which pulls from splunk_config, but that isn't set within forwarder.  This pull just adds support for that.
The spec test for the forwarder class just has the compile with deps, so I didn't add anything to test values of the path for it.

Allow forwarder to fully support alternate install directories

---

manifests/platform/posix.pp

When splunk is started the first time on 7.1.x (and
higher) there is input expected, disable this with
--no-prompt. Fixes #186
Installation of 7.1.x RPM's ask for input of a password
Fixes issue #186

This commit fixes the error in startup 7.1.x

---

README.md
manifests/platform/posix.pp

Triggering the exec resource based on the presence of the etc/auth/server.pem prevents the exec resource from being called after splunk has been upgraded, unless we're willing to delete the server.pem file.
The ftr file is an improved trigger for determining when to run the license_splunkforwarder exec resource. The ftr file always exists immediately following an install of splunk or splunkforwarder. The install could be a first time install or an upgrade. Once the license agreement has been accepted the ftr file is removed.
Upgrades don't trigger license_splunkforwarder exec resource #198

Improve ftr license agreement

---

manifests/forwarder.pp
spec/classes/forwarder_spec.rb

Splunk environments where the majority of the configuration is handled by splunk do not necessarily like these defaults. So allow a way to not provide them. Either by setting undef or passing empty (nil) from hiera.

Allow empty local and outputs files to keep centralized Splunk happier.

---

.sync.yml
lib/facter/splunk_version.rb
lib/facter/splunkforwarder_version.rb
spec/spec_helper.rb
spec/unit/facter/splunk_version_spec.rb
spec/unit/facter/splunkforwarder_version_spec.rb

Adds `splunkfowarder_version` fact that works for both Linux and Windows.

Add splunkforwarder_version fact

---

README.md

The Types `splunk_deploymentclient` and `splunkforwarder_deploymentclient` exist in the code, but are not listed in the README.

Add documentation for two file types.

---

README.md

Splunk_serverclass was already declared but was not used anywhere. This adds the line to the README.
Closes #218

Add splunk_serverclass documentation to README

---

lib/puppet_x/puppetlabs/splunk/type.rb
lib/puppet_x/voxpupuli/splunk/util.rb
spec/acceptance/splunk_enterprise_spec.rb
spec/acceptance/splunk_forwarder_spec.rb
spec/unit/puppet/type/splunk_types_spec.rb
spec/unit/puppet_x/voxpupuli/splunk/util_spec.rb

When splunk is started, it automatically encrypts certain values when it
finds them in config files.  To stop puppet reverting these changes,
I've overriden `insync?` so that it performs the decryption before
comparing.
Currently only implemented for splunk >= 7.2
Based on description of algorithm in this python based project.
https://github.com/HurricaneLabs/splunksecrets

Compare decrypted values to see if they are insync

---

manifests/params.pp

The value for kernel, osfamily and os.family in Puppet is 'windows' for the Windows OS, not 'Windows' with a capital W.

fix osfamily = 'windows' and kernel = 'windows' in lowercase

---

manifests/addon.pp
spec/defines/addon_spec.rb

Removes declaration of Class[splunk::params] since it should already be in scope and declared by either Class[splunk::enterprise] or Class[splunk::forwarder] and removes an unnecessary test of an empty hash. Modifies Splunk::Addon spec test to address the removal of Class[splunk::params].

Address post-merge comments on PR #224

---

manifests/addon.pp

Commit sets user and group of expanded splunkbase archive and local directory to same as what's used for splunk installation

Set user and group for addon installation

---

manifests/params.pp

adds the secret_file parameter to Windows
the secret_file parameter was missing for the Windows case in params.pp which was causing a catalog compilation failure with the following error:
```Error while evaluating a Resource Statement, Class[Splunk::Forwarder]: parameter 'secret_file' expects a Stdlib::Absolutepath = Variant[Stdlib::Windowspath = Pattern[/^(([a-zA-Z]:[\\\/])|([\\\/][\\\/][^\\\/]+[\\\/][^\\\/]+)|([\\\/][\\\/]\?[\\\/][^\\\/]+))/], Stdlib::Unixpath = Pattern[/^\/([^\/\0]+\/*)*$/]] value, got Undef```

add secret_file parameter to Windows

---

manifests/enterprise/config.pp

This commit adds relationship that's getting lost in a sea of
containment layers that ensures Splunk services are restarted
before the test checks for success or not.
Without this the test fails in certain random situations and
likely in a limited number of real world cases as well.

Fix flaky acceptance tests

---

manifests/enterprise.pp
manifests/enterprise/service.pp
manifests/enterprise/service/nix.pp
manifests/forwarder.pp
manifests/forwarder/service.pp
manifests/forwarder/service/nix.pp
manifests/params.pp
spec/classes/enterprise_spec.rb
spec/classes/forwarder_spec.rb

Fix execution of `splunk enable boot-start` to actually work with systemd systems and also to not specify `-user` when root is the user and also supporting systemd to avoid unnecessary `chown` lines in unit file per 7.3.2 docs.
Also fix order of service subclasses so they are applied after packages and configs.
Fixes #262 
Fixes #263

Fix systemd support and service subclass ordering

---

manifests/forwarder/service/nix.pp
spec/classes/forwarder_spec.rb

Based on Splunk docs (https://docs.splunk.com/Documentation/SplunkCloud/8.0.0/User/UpgradeyourForwarders) the way to upgrade forwarders is manually or with a script and that script essentially stops and then starts splunk with `--accept-license --assume-yes`. This tries to mimic that behavior.  The Exec should only be triggered if the forwarder is already installed.
Output from running this on my test and dev systems:
```
Notice: /Stage[main]/Splunk::Forwarder::Install/Package[splunkforwarder]/ensure: ensure changed '7.3.2-c60db69f8e32' to '0:7.3.3-7af3758d0d5e' (corrective)
Info: /Stage[main]/Splunk::Forwarder::Install/Package[splunkforwarder]: Scheduling refresh of Exec[splunk-forwarder-accept-tos]
Notice: /Stage[main]/Splunk::Forwarder::Service::Nix/Exec[splunk-forwarder-accept-tos]: …
```

Support upgrading splunk forwarding and accepting ToS

---

manifests/forwarder/password/seed.pp

Currently when seeding passwords for splunk::forwarder, it will continually re-seed unless you also have the splunk enterprise installed. This should resolve that.
n/a

Check if splunk forwarder was already installed when seeding password.

---

manifests/params.pp
metadata.json

Add support for OpenSUSE. Tested on OpenSUSE 15

Add support for OpenSUSE

---

spec/defines/addon_spec.rb

Fix rspec 3.10 failures

---

spec/classes/enterprise_spec.rb

This came up during https://github.com/voxpupuli/puppet-splunk/pull/298

adopt test to newer rspec-puppet syntax

---

spec/classes/forwarder_spec.rb

dad494dd9e606b268c43bb892bb119fd0465e31f did the same thing for the enterprise spec. It ends up being the same test, but with less code.

Use a more concise rspec-puppet syntax

---

manifests/params.pp

The systemd service file locations are documented here:
https://docs.splunk.com/Documentation/Splunk/8.1.0/Admin/RunSplunkassystemdservice#Configure_systemd_using_enable_boot-start
Also the splunk installer looks for this file, not the symlink to it.

Fix systemd service file locations to documented locations

---

manifests/enterprise/install/nix.pp
manifests/forwarder/install.pp

ensure_packages uses all parameters for the hash, but other instances
of ensure_packages['net-tools'] do not all specify exact this before option.
See https://tickets.puppetlabs.com/browse/MODULES-8733
Fixes #275

Workaround a change in behavior of ensure_packages with stdlib

---

manifests/forwarder.pp
manifests/params.pp
metadata.json
spec/classes/forwarder_spec.rb

Add support for FreeBSD. Tested on FreeBSD 12.1

Add support for FreeBSD

---

manifests/enterprise.pp

This PR replaces the incorrect parameter name in the documentation for `splunk::enterprise::web_httpport`.
N/a

Correct web_httpport field name

---

manifests/params.pp

Add ability to override default-host configuration. The default-host configuration is used to control the "host" property which Splunk will use to identify the forwarder. The current behaviour forces the default-host to match the server's $HOSTNAME. In my environment we prefer to customise this name to identify the region and environment for the forwarder (info we don't normally include in the server's hostname).
The default behaviour is maintained so this shouldn't break any existing setup. It just adds the ability to override it if required.
N/A

Add ability to override default-host configuration

---

.sync.yml
.travis.yml
metadata.json

CentOS 6 is EOL. The CentOS people also removed their stuff from the
mirrors so our acceptance tests do not pass anymore.

Drop CentOS 6 support

---

manifests/enterprise.pp
manifests/enterprise/password/manage.pp
manifests/enterprise/password/seed.pp
manifests/forwarder.pp
manifests/forwarder/password/manage.pp
manifests/forwarder/password/seed.pp

I fixed some wrong puppet-strings tags. Sadly I cannot regenerate the
README.md??
```
rake aborted!
NoMethodError: undefined method `any?' for nil:NilClass
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-splunk/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings/yard/code_objects/type.rb:153:in `parameters'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-splunk/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings/yard/code_objects/type.rb:184:in `to_hash'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-splunk/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings/markdown/resource_types.rb:8:in `map!'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-splunk/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/pup …
```

update puppet-strings documentation

---

REFERENCE.md
manifests/enterprise/install/nix.pp
manifests/forwarder/install.pp
manifests/params.pp
spec/classes/enterprise_spec.rb

I believe this is a controversial pull request.
net-tools is very common dependency, and in a huge code base with many dependencies most likely it will be already declared somewhere.
I've introduced a flag `manage_net_tools` in params.pp with a default `true`, which will keep working as it is for everyone, but will allow projects like ours to mark it as `false` when net-tools is already managed somewhere else.
Thanks.
Manuel

add option to manage net-tools package

---

metadata.json

Puppet 5 has reached EOL, update metadata.json.
#307 added support for Ubuntu 20.04 for which no Puppet 5 package is available.  Dropping support for Puppet 5 should allow the test suite to be green again
n/a

Drop Puppet 5, add Puppet 7 support

---

lib/facter/splunkforwarder_version.rb
spec/unit/facter/splunkforwarder_version_spec.rb

This prevents facter from getting stuck in an interactive session.

Safer version check

---

manifests/enterprise.pp
manifests/enterprise/config.pp
manifests/enterprise/password/seed.pp
manifests/forwarder.pp
manifests/forwarder/config.pp
manifests/forwarder/password/seed.pp
manifests/params.pp
spec/acceptance/splunk_enterprise_spec.rb
spec/classes/enterprise/password/seed_spec.rb
spec/classes/forwarder/password/seed_spec.rb
templates/user-seed.conf.epp

Allow `user-seed.conf` to have a not-hardcoded userid instead of 'admin.
The `user-seed.conf` file sets a default local user/password (admin/changeme by default).  Some security policies wish for you to have only non-default userids.  At present, the existing module doesn't allow that.
The testing is a little lax here because there was not great testing on these classes to begin with.  Sorry.

Allow user-seed.conf to set a username besides 'admin'

---

manifests/addon.pp
spec/defines/addon_spec.rb

Add `extract_command` as a parameter to `splunk::addon`
https://dev.splunk.com/enterprise/docs/releaseapps/packageapps/ - "An app package is a compressed tar archive, or tarball, with a .spl, .tgz, or .tar.gz file extension"
The `archive` module (which this module calls) does not know what a `.spl` file is, and will refuse to untar it.  But it's simply a tarball.
`.spl`, as an extension, is not unique to Splunk (it means 'spool' in some contexts) so it's probably not smart to edit the `archive` module to 'know' about `.spl`, just to satisfy one vendor.
This commit is intended to allow you to keep a `.spl`-named source file, and for puppet know what to do with it.
The alternate to rename the file to `.tgz` is possible, but somewhat non-obvious for users, who may want to keep their spl …

Add extract_command as a parameter to splunk::addon

---

manifests/forwarder/service/nix.pp
spec/classes/forwarder_spec.rb

Fixes #310
Fixes for permission startup when running as root user.
Fixes #310 - it appears the default user for splunk has changed from root to splunk at some point. The default being root meant not explicitly specifying the user still worked until the default changed to splunk. The resulted in the module config having root, file ownership having root, but the service starting as splunk due to it not being explicitly specified.

Explicitly set user on call to 'splunk enable boot-start'

---

manifests/forwarder/service/nix.pp

Puppet on Solaris defaults to the SMF provider for services. Splunk is still using init scripts (as of latest version 9.0.0).
Puppet attempts to enable the service, which causes a catalog failure:
Error: Could not start Service[splunk]: Execution of '/usr/sbin/svcadm enable -rs splunk' returned 1: svcadm: Pattern 'splunk' doesn't match any instances
Error: /Stage[main]/Splunk::Forwarder::Service/Service[splunk]/ensure: change from 'stopped' to 'running' failed: Could not start Service[splunk]: Execution of '/usr/sbin/svcadm enable -rs splunk' returned 1: svcadm: Pattern 'splunk' doesn't match any instances
No bug logged for this

Use init provider on solaris when managing service

---

REFERENCE.md
manifests/forwarder.pp
manifests/forwarder/install.pp
manifests/params.pp

enable the puppet-archive `allow_insecure` parameter

---

README.md

Travis was replaced with GitHub Actions. Let's fix the badge.

[ci skip] Fix CI badge

---

lib/puppet_x/puppetlabs/splunk/type.rb
spec/unit/puppet/type/splunk_types_spec.rb

Before it was only possible to set an encrypted value by setting it in plain text. If the encrypted value was given, there was and endless re-apply happening because Splunk encrypts the values during boot time thus changing the value.
Now it's also possible to set the values by providing the encrypted value directly.
Fixes #284 (Maybe #197 ?)

Allow the user to set encrypted values directly

---

lib/facter/splunk_version.rb
spec/unit/facter/splunk_version_spec.rb

Interactive Puppet runs can hang on a facter Splunk version check immediately following a Splunk Enterprise package upgrade. This change makes the version check arguments in splunk_version.rb match those added to the version check in splunkforwarder_version.rb in commit 5778673ee.
n/a

Safer Splunk Enterprise version check

---

README.md

- Bump the versions of Splunk in the README to be an up-to-date version of Splunk. (So it doesn't seem like this module would only support installing/running Splunk 7.x)
- Fix typo "the the"
- Update the "limitations" (Splunk and puppet versions etc)

Miscellaneous README improvements

---

manifests/enterprise/service/nix.pp
spec/acceptance/splunk_enterprise_spec.rb

When upgrading, there was an issue with accepting the license of the new version. Thus symptoms described in #339 happened. To ensure we have a clean upgrade we need to re-enable boot-start after the upgrade.
This will also apply the correct systemd service file when upgrading, before it was just the service file of the originally installed version. It never changed.

Fix upgrading Splunk Enterprise

---

README.md

It wasn't clear with the current README.md that you are able to use this module without setting up the whole Puppet file share. It will download the installers from Splunk's website if you don't specify a source.

Updated README.md to make it clear that this module can download directly from the Splunk website

---

CHANGELOG.md
metadata.json

Major relase due to:
- Support for Puppet 6 dropped.
- Defaults changed: Splunk version, build and user. This could impact users that have set Splunk to a 8.x or 9.x version that used the previous "root" user as a default.

Prepare for 10.0.0 release

---

manifests/params.pp
spec/classes/enterprise_spec.rb
spec/classes/forwarder_spec.rb

The `splunk.secret` file on Linux is located at `$SPLUNK_HOME/etc/auth` instead of `$SPLUNK_HOME/etc/` as per [Splunk documentation](https://docs.splunk.com/Documentation/Splunk/9.3.0/Security/Deploysecurepasswordsacrossmultipleservers) since at least v7.0.0 through v9.3.0
Fixes #324

Correct `splunk.secret` path

---

REFERENCE.md
manifests/forwarder.pp
manifests/forwarder/service.pp
manifests/params.pp
spec/acceptance/splunk_forwarder_spec.rb
spec/classes/forwarder_spec.rb

On windows we need to set delayed for the service
Issue_383: Make the ensure and enable parameter of the splunk forwarder service configurable
We need to set enable to delayed on windows servers
Fixes #383

Issue #383: Add ensure and enable parameter for forwarder service

---

manifests/params.pp
spec/spec_helper_acceptance.rb

this change is to change the file name of the debian packer after version 9.4.0
it was: -linux-2.6-
it needs to be: -linux-
the is a problem when trying to install splunk 9.4.0 in ubuntu hosts due to package file name change
Fixes #392

Debian: Add support for Splunk 9.4 and newer
