manifests/forwarder.pp, manifests/init.pp
Collectors behave strangely with arrays, so use realize and update
dependencies as needed.
=> MODULES-2448 - Improved collector compatibility

manifests/forwarder.pp, manifests/params.pp
=> Adds param for ensuring forwarder can be the latest argument

manifests/init.pp, manifests/params.pp
Allows for setting of `ensure` on the server package
=> Server ensure

lib/puppet/type/splunk_props.rb, lib/puppet/type/splunk_transforms.rb, lib/puppet/type/splunkforwarder_transforms.rb
This just fixes small docs errors.
=> Correct the descriptions of existing splunk types

lib/puppet/provider/splunk_authentication/ini_setting.rb, lib/puppet/provider/splunk_authorize/ini_setting.rb, lib/puppet/provider/splunk_distsearch/ini_setting.rb, lib/puppet/provider/splunk_indexes/ini_setting.rb, lib/puppet/provider/splunk_limits/ini_setting.rb, lib/puppet/provider/splunk_web/ini_setting.rb, lib/puppet/type/splunk_authentication.rb, lib/puppet/type/splunk_authorize.rb, lib/puppet/type/splunk_distsearch.rb, lib/puppet/type/splunk_indexes.rb, lib/puppet/type/splunk_limits.rb, lib/puppet/type/splunk_web.rb
- Adds a number of missing types/provider for configuring Splunk based on its set of ini config files.
=> Create additional Splunk types/providers

README.markdown
- This is a really simple fix.
=> Fix typo in README.

lib/puppet/type/splunk_config.rb, spec/spec_helper.rb, spec/splunk_data.rb, spec/system/forwarder_spec.rb, spec/unit/puppet/type/splunk_config_spec.rb, spec/unit/puppet/type/splunk_types_spec.rb
* Added rspec tests for splunk types
* Added rspec tests for splunk_config
* Bugfix: splunk_input file_path not being set
* Bugfix: calling provider file_path method from a variable
=> Added rspec tests for types and splunk_config and other bugfixes

CHANGELOG.md, metadata.json
=> Prepped 5.0.1

CHANGELOG.md, metadata.json
=> prepped 5.0.2

README.md, metadata.json
Just kidding nothing to see here... I forgot that github redirects repos
:(
This reverts commit abaed56cd7b4775bef0ba3b5b318584e33d9d0f9.
=> Revert "Release deprecated version"

README.md
puppet module install puppetlabs-splunk installs the v99.99.99 version, should be updated to reflect current ownership
=> Update README.md from puppetlabs-splunk

manifests/platform/posix.pp
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
=> Remove unneded blank lines

manifests/platform/posix.pp
=> Ensure /etc/init.d/splunk is created before splunk services

manifests/forwarder.pp, manifests/init.pp
=> Lint fixes

CHANGELOG.md, metadata.json
=> Bump release for 6.0.0

manifests/init.pp
=> Fix resource ordering in splunk class so that splunk types will properly notify services

README.md
Hello 😃
This is nothing urgent by my OCD is going nuts with this little typo.
Regards
FYI, this is my first commit to an open source project so I hope I did this right. If not feel free to show me the right way :)
=> Fix typo in extension filename

.fixtures.yml, metadata.json
closes #122 
@bastelfreak  can you approve and merge this?
=> Added missing concat dependency to metadata.json + .fixtures.yml

CHANGELOG.md, metadata.json
Can somone review the changelog and see if i need to update any titles/labels.
There exist only features and bugs fixes in this release so i did a minor bump
=> Release v6.1.0

CHANGELOG.md, metadata.json
Cutting new release.  Did a bump on the minor since the public API didn't change and i simply updated a dependency.
=> 6.2.0 Release

manifests/init.pp
=> Manage splunk_uiprefs like other configuration types

lib/puppet/provider/splunk_alert_actions/ini_setting.rb, lib/puppet/type/splunk_alert_actions.rb, lib/puppet/type/splunk_config.rb, manifests/init.pp
@treydock @bastelfreak
This is a rebase of #94
Lets get this merged before it falls behind again.
=> Add splunk_alert_actions type.

lib/puppet/provider/splunk_deploymentclient/ini_setting.rb, lib/puppet/provider/splunkforwarder_deploymentclient/ini_setting.rb, lib/puppet/type/splunk_config.rb, lib/puppet/type/splunk_deploymentclient.rb, lib/puppet/type/splunkforwarder_deploymentclient.rb, manifests/forwarder.pp, manifests/init.pp
@treydock @bastelfreak
This is a rebase of #94
Lets get this merged before it falls behind again.
=> Add deploymentclient types

CHANGELOG.md, metadata.json
No Breaking changes and just features :)
=> v6.3.0 release

CHANGELOG.md, metadata.json
Doing a release so other people don't try and use the new types introduced last release and start creating issues.
=> Release v6.3.1

manifests/addon.pp
=> replace validate_string with assert_type

CHANGELOG.md, metadata.json
=> release 7.1.0

metadata.json
I don't think the changes over there should impact anything.
=> Allow this module to be installed with puppet-archive 3.0.0

CHANGELOG.md, metadata.json
=> release 7.2.0

.msync.yml, .overcommit.yml, .sync.yml, .travis.yml, Gemfile
=> modulesync 2.0.0

lib/puppet/type/splunk_config.rb
Add splunkforwarder_limits to set_provider_paths function
Fixes #202
=> Fixes #202

CHANGELOG.md, metadata.json
=> release 7.3.0

.msync.yml, .sync.yml, .travis.yml, Dockerfile, Gemfile, Rakefile
=> modulesync 2.7.0

manifests/addon.pp, manifests/enterprise.pp, manifests/enterprise/config.pp, manifests/enterprise/install.pp, manifests/enterprise/install/nix.pp, manifests/enterprise/service.pp, manifests/enterprise/service/nix.pp, manifests/forwarder.pp, manifests/forwarder/config.pp, manifests/forwarder/install.pp, manifests/forwarder/service.pp, manifests/forwarder/service/nix.pp, manifests/init.pp, manifests/params.pp
Commits updates or adds "puppet strings" documentation that adheres to style guide and semantics understood by YARD. Does not prioritize the correctness or verifying the validity of documentation...
Close examination of documentation validity to be handled after manifests are consistently documented.
=> Documentation style updates

.msync.yml, .rubocop.yml, .travis.yml, Gemfile, Rakefile, lib/puppet/type/splunk_config.rb, spec/spec_helper.rb, spec/unit/puppet/type/splunk_types_spec.rb
=> modulesync 2.10.1

.github/CONTRIBUTING.md, .msync.yml, .rubocop.yml, Gemfile, Rakefile, lib/puppet/type/splunk_config.rb, spec/spec_helper.rb, spec/unit/puppet/type/splunk_types_spec.rb
=> modulesync 3.0.0

README.md
Can we also validate the Limitations for current relevance?
=> (docs) cleaned up the TBD sections.

.github/SECURITY.md, .msync.yml, .rubocop.yml, .travis.yml, Gemfile, manifests/addon.pp, manifests/enterprise.pp, manifests/enterprise/config.pp, manifests/enterprise/install.pp, manifests/enterprise/install/nix.pp, manifests/enterprise/password/manage.pp, manifests/enterprise/password/seed.pp, manifests/enterprise/service.pp, manifests/enterprise/service/nix.pp, manifests/forwarder.pp, manifests/forwarder/config.pp, manifests/forwarder/install.pp, manifests/forwarder/password/manage.pp, manifests/forwarder/password/seed.pp, manifests/forwarder/service.pp, manifests/forwarder/service/nix.pp, manifests/init.pp, manifests/params.pp
=> modulesync 3.0.0 & puppet-lint updates

metadata.json
=> Add Ubuntu 18.04/20.04 support

metadata.json
=> Drop EOL Debian 8; Add Debian 9/10 support

metadata.json
=> Allow latest dependencies

.editorconfig, .github/CONTRIBUTING.md, .github/workflows/ci.yml, .github/workflows/release.yml, .gitignore, .msync.yml, .overcommit.yml, .pmtignore, .rspec, .rspec_parallel, .rubocop.yml, .yardopts, Dockerfile, Gemfile, Rakefile, spec/classes/enterprise_spec.rb, spec/spec_helper.rb
This is a showcase for:
- https://github.com/voxpupuli/modulesync_config/pull/732
=> Update from voxpupuli modulesync_config

CHANGELOG.md, metadata.json
=> Release 9.1.1

metadata.json
Updates splunk module against current dependencies
=> Allow inifile 6.x, concat 9.x, archive 7.x

metadata.json
=> Add Rocky and AlmaLinux 8 and 9 support

metadata.json
=> Add EL 8 and 9 support

manifests/enterprise/install/nix.pp, manifests/forwarder/install.pp, metadata.json
Uses the stdlib9 namespaced function for `ensure_packages`, raises the lower limit.
=> Use namespaced ensure_packages, require puppetlabs/stdlib 9.x

manifests/params.pp
See https://docs.splunk.com/Documentation/Forwarder/9.1.3/Forwarder/KnownIssues.
Replaces #352
=> Add workaround for Windows based Splunk UF 9.1.3 known issue

manifests/params.pp
Support for downloading the aarch64 packages of Splunk forwarder/server
#379
=> Support downloading RedHat aarch64 packages

REFERENCE.md, lib/puppet/type/splunk_config.rb, manifests/enterprise/install.pp, manifests/enterprise/password/manage.pp, manifests/enterprise/password/seed.pp, manifests/enterprise/service.pp, manifests/forwarder/config.pp, manifests/forwarder/install.pp, manifests/forwarder/password/manage.pp, manifests/forwarder/password/seed.pp, manifests/forwarder/service.pp, manifests/params.pp, types/entinstalloptions.pp, types/fwdinstalloptions.pp
Resolve some puppet-strings warnings
=> Resolve puppet-strings documentation warnings
